name: AKS Deploy

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
      appEnv:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  Aks_Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout shared repo
        uses: actions/checkout@v4
        with:
          repository: azure-prep/roboshop-helm
          ref: main
          path: helm

      - name: Import Secrets
        # Use the latest version of the action
        uses: hashicorp/vault-action@v2
        id: import-secrets
        with:
          url: http://vault-int.azdevopsb1.online:8200
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;

      - name: helm deploy
        run: |
          cd helm
          export TF_VAR_ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
          export TF_VAR_ARM_CLIENT_SECRET="${{ env.ARM_CLIENT_SECRET }}"
          export TF_VAR_ARM_TENANT_ID="${{ env.ARM_TENANT_ID }}"
          az login --service-principal  --username ${TF_VAR_ARM_CLIENT_ID} --password ${TF_VAR_ARM_CLIENT_SECRET} --tenant ${TF_VAR_ARM_TENANT_ID};
          az acr login --name azuredevopsb84.azurecr.io
          az aks get-credentials --resource-group roboshop-${{inputs.resource_group_name}} --name  main-${{inputs.appEnv}} --overwrite-existing
          echo ${{ github.sha }}
          kubectl create ns app || true
          argocd login argocd-dev.azdevopsb1.online --insecure --username admin --password $(kubectl get secrets argocd-initial-admin-secret -n argocd  -o=jsonpath='{.data.password}' |base64 --decode)   --grpc-web
          argocd app create ${{ inputs.appName }} --repo https://github.com/azure-prep/roboshop-helm.git --path . --dest-namespace app --dest-server https://kubernetes.default.svc --values env-dev/${{ inputs.appName }}.yaml --helm-set appTag=${{ github.sha }} --upsert
          argocd app sync ${{ inputs.appName }}