name: CI - dev

on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import Secrets
        # Use the latest version of the action
        uses: hashicorp/vault-action@v2
        id: import-secrets
        with:
          url: http://vault-int.azdevopsb1.online:8200
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
            roboshop-infra/data/sonarqube SONARQUBE_TOKEN | SONARQUBE_TOKEN ;

      - name: SonarQube Scan - Java
        if:  inputs.appType == 'Java'
        run: |
          echo /home/github/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://sonarqube.azdevopsb1.online:9000 -Dsonar.token=${SONARQUBE_TOKEN} -Dsonar.projectKey=roboshop-${{ inputs.appName }} -Dsonar.java.binaries=./target/
          ### -Dsonar.qualitygate.wait=true
          ### Above option to fail the pipeline, As of now we are not doing it.

      - name: SonarQube Scan - NonJava
        if:  inputs.appType != 'Java'
        run: |
          /home/github/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://sonarqube.azdevopsb1.online:9000 -Dsonar.token=${SONARQUBE_TOKEN} -Dsonar.projectKey=roboshop-${{ inputs.appName }}

      - name: Build application
        run: |
          if [ "${{ inputs.appType }}" = "Nodejs" ]; then
            npm install
          elif [ "${{ inputs.appType }}" = "Java" ]; then
            mvn package
          fi

      - name: Docker build
        run: |
          export TF_VAR_ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
          export TF_VAR_ARM_CLIENT_SECRET="${{ env.ARM_CLIENT_SECRET }}"
          export TF_VAR_ARM_TENANT_ID="${{ env.ARM_TENANT_ID }}"
          az login --service-principal  --username ${TF_VAR_ARM_CLIENT_ID} --password ${TF_VAR_ARM_CLIENT_SECRET} --tenant ${TF_VAR_ARM_TENANT_ID};
          az acr login --name azuredevopsb84.azurecr.io
          docker build -t azuredevopsb84.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }} .
          trivy image azuredevopsb84.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }} --severity HIGH,CRITICAL --ignore-unfixed --exit-code 0
          docker push azuredevopsb84.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }}