name: CI - dev

on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string

jobs:
  NodeJs_Build:
    if: ${{ inputs.appType == 'Nodejs' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build  NodeJS app
        run: |
          npm install
          docker ps

  Java_Build:
    if: ${{ inputs.appType == 'Java' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Java app
        run: |
          mvn package   
