name: CI - dev

on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string

jobs:
  NodeJs_Test:
    if: ${{ inputs.appType == 'Nodejs' }}
    runs-on: self-hosted
    steps:
      - name: Test
        run: |
          echo "Tests success"

  Java_Test:
    if: ${{ inputs.appType == 'Java' }}
    runs-on: self-hosted
    steps:
      - name: Test
        run: |
          echo "Tests success"
